### ISSUE TITLE
No BKON SDK for iOS?

### ISSUE THREAD

**Issue by inigo333** [bkon-connect/BKON-Basic-SDK-iOS#2]
Hi, I was trying to download the BKON SDK for iOS on this repository, but the read me file said the following:

`The BKON Basic SDK has evolved into the BKON Advanced SDK.
The BKON Advanced SDK is hosted here: http://bkon.com/sdk`

However, when going there, I am redirected to
https://bkon.com/the-physical-web/phynet/
and no SDK can be found there.

Where can I found one?

Thanks

**Comment by rochforp** [comment]
Hey @inigo333 we moved our new sdk over to here https://www.phy.net/sdk/physical-web-sdk-ios/ . I'll update this for the greater good. Thanks for bringing this to our attention 👍
